- name: backend files
  become: true
  copy:
    src: /root/project/artifact.tar.gz
    dest: /home/ubuntu/artifact.tar.gz

- name: unarchive
  shell: |
    cd /home/ubuntu/
    tar xzvf artifact.tar.gz
    pwd
    ls -ltr

- name: start job  
  shell: |
    pwd
    cd /home/ubuntu/backend
    npm install
    pm2 stop default
    pm2 start npm -- start  