- name: Copy zipped file
  shell: |
    ls /home/ubuntu
- name: Unpacking zipped files
  unarchive:
    src: "artifact.tar.gz"
    dest: /home/ubuntu

- name: Copy artifact.tar.gz to EC2
  copy:
    src: "artifact.tar.gz"
    dest: "/home/ubuntu/artifact.tar.gz"

- name: Executing node
  shell: |
    ls /home/ubuntu
    # tar -xf artifact.tar.gz
    npm install
    pm2 stop default
    pm2 start npm -- start
